const IMAGES = {
  HomeSVG: require('../assets/svg/home.svg'),
  BLoomyLogo: require('../assets/images/logo.png'),
  LoginPng: require('../assets/images/login.png'),
  RegisterImg: require('../assets/images/register.png'),
  Intro1: require('../assets/images/introo1.png'),
  Intro2: require('../assets/images/introo2.png'),
  Intro3: require('../assets/images/introo3.png'),
  Intro4: require('../assets/images/introo4.png'),
  Mothers: require('../assets/images/mother.png'),
  Wedding: require('../assets/images/wedding.png'),
  Graduation: require('../assets/images/Graduation.png'),
  Birthday: require('../assets/images/Birthday.png'),
  flower1: require('../assets/images/flower1.png'),
  flower2: require('../assets/images/flower2.png'),
  flower3: require('../assets/images/flower3.png'),
  flower5: require('../assets/images/flower5.png'),
  splash: require('../assets/images/logo.png'),
  flower4: require('../assets/images/flower4.png'),
  VISa: require('../assets/images/Mastercard-Logo-PNG8.png'),
  Paypal: require('../assets/images/PayPal.svg.png'),
  Mastercard: require('../assets/images/Visa-Logo-PNG7.png'),
  Success: require('../assets/images/check.png'),
  CartEmpty: require('../assets/images/cartempty.png'),
  Profile: require('../assets/images/profile.jpg'),
};
export default IMAGES;
